# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


stages:

 - stage: Build_A
   displayName: Build stage
   jobs:
    - job: Build
      displayName: Build
      pool: 
        vmImage: 'ubuntu-latest'
        container: ubuntu:18.04
      steps:
        - script: |
            echo "Hello, world!"
            ls -la
            cat /etc/os-release
            echo $hostname
          displayName: 'Run a one-line script'
        
 - stage: Build_B
   displayName: Build stage
   jobs:
    - job: Build
      displayName: Build
      pool: 
        vmImage: 'ubuntu-latest'
        container: ubuntu:18.04
      steps:
        - script: |
            echo "Hello, world!"
            ls -la
            cat /etc/os-release
            echo $hostname
          displayName: 'Run a one-line script'
